### ISSUE TITLE
silent output on daisy seed

### ISSUE THREAD

**Issue by nlscelli** [amcerbu/DaisySTFT#1]
Hi!
thanks for the very interesting repo :)

I am having some troubles getting any output. The code compiles and flashes to daisy just fine, but there is no output at all. I am feeding it a mono line level signal in audio in pin 2 and outputting to audio out pin 2.

Would you have any suggestion?

Thanks!

Nicolas

**Comment by hemmer** [comment]
Having a similar issue, how did you resolve?

**Comment by amcerbu** [comment]
The program only listens on the left input channel; it mirrors the outputs on both left and right channels.  What's your hardware setup?

If you want to take input from the right channel instead, change line 56 in `spectral.cpp` to `stft->write(in[i + 1]);`.

**Comment by hemmer** [comment]
Thanks, it ended up being something silly for me, I missed it was for daisy seed (not daisy patch submodule) so which I updated that it worked. 🤦 

I also needed `#include <functional>` on `wave.h` to compile on Mac.

Thanks again for this example, much appreciated!
