### ISSUE TITLE
Example Request

### ISSUE THREAD

**Issue by GuitarML** [amcerbu/DaisySTFT#3]
This stft code is fantastic! This is not an issue with the code, it ran fine for me on the daisy seed, but Im trying to figure out how to best implement some effects. How would one make use of the "middle" buffer? Or is this an intermediate stage that you don't reference in the function call. I'd like to have a buffer that persists across function calls, for example to hold energy data for a freeze effect. Should I make my own buffer of size N, or is this what the middle buffer should be used for? 

I just getting up to speed on stft's so bear with me, I see that the buffers are size 2 * N * laps, which 32k+, but in your denoise example you only need to loop over the first N (4096) samples to get the real/imag parts. Is that the only part of the buffers we care about in the function call? 

Thanks!

**Comment by amcerbu** [comment]
Glad you're finding the STFT code helpful! The project isn't so well-commented, for which I apologize. The Fourier object reads time-domain data from the `in` buffer and writes frequency-domain information into the `middle` buffer. The FFT callback then transforms the frequency-domain content of the `middle` buffer and stores it in the `out` buffer, which then is inverse-Fourier-transformed and turned into time domain data stored in the `in` buffer again. 

If you're wanting to do a spectral freeze thing, you might find my phase vocoder example useful: https://github.com/amcerbu/StrobeSpectralGranular/blob/main/fourier/spectral.cpp. It's all in the `pitch_shift` function (which is still a work in progress – it detects frequencies, but doesn't resynthesize). 

There's definitely some optimization that could be done in DaisySTFT – I've been meaning to get back to this project but have had other things on my plate!

**Comment by GuitarML** [comment]
@amcerbu that makes sense now, thanks! So the "in" buffer in the custom function is actually the data from the "middle" buffer, and "out" is "out".

I tried running your granny program on the bksheperd pedal, but it was over the FLASH limit by a percent or two, so I tried compiling to SRAM. It seemed to load the screen correctly, but then froze, I'm guessing it's too slow to run from SRAM. Am I missing something for running that effect?

I'm actually trying to replicate this reverb effect from this forum (written in the Reaper DAW's scripting language):
https://forum.cockos.com/showthread.php?t=225955

Here is what I have, but running this just seems to give me stuttering of the clean signal:

"reverb_energy" is defined as ```reverb_energy[N/2]``` and initialized to 0.  vdamp, vmix, and vdecay are controlled by knobs.
```
inline void reverb(const float* in, float* out)
{
        // Reverb logic based on code by geraintluff in this forum:
        // https://forum.cockos.com/showthread.php?t=225955
        // Here I only use mono though

	// convenient constant for grabbing imaginary parts
	static const size_t offset = N / 2; // equals 2048

	for (size_t i = 0; i < N; i++)  // loop 0 to 4096
	{
		out[i] = 0; // Is this necessary? It was in the original example code

	}

	for (size_t i = 0; i < N / 2; i++)  // loop i from 0 to 2047
	{

            float fft_size = N / 2;
            float fft_bin = i + 1;

            float real = in[i];
            float imag = in[i + offset];
            float reverb_amp = 0.0;

            float energy = real * real + imag * imag;

            // Amplitude from energy
            reverb_amp *= vmix * sqrt(reverb_energy[i]);
            if (fft_bin / fft_size > vdamp) {

                // Reduce amplitude by 1/f
                reverb_amp *= vdamp * fft_size/fft_bin;
            }

            // Add random phase reverb energy
            float random_phase = rand()*2*PI;
            real += reverb_amp * cos(random_phase);
            imag += reverb_amp * sin(random_phase);

            // Add current energy to reverb
            reverb_energy[i] += energy / laps; // laps=4 "overlap factor"

            // Decay reverb
            float reverb_decay_factor = 1/vdecay;
            reverb_energy[i] *= 1.0 - reverb_decay_factor;

            // TODO Is this right for Mono? The code from forum does some left/right mixing for stereo
            out[i] = real;
            out[i + offset] = imag;

	}
}
```

Does anything stand out as to what I might be doing wrong? I will check out your pitchshift code, thanks!

**Comment by amcerbu** [comment]
@GuitarML That's strange that you couldn't load the `granny` program! It flashes fine to my Daisies. Are you using the `makefile` included with the project? I removed an unnecessary header file and committed just now – let me know if that works. I'm also happy to provide the compiled binaries. 

As far as this reverb example, I can't tell what this should do just by looking. One thing that sticks out – I don't think `reverb_amp` ever takes a nonzero value, since you initialize it to zero, and then multiply it by a series of values. Should it start out at `1.0`? Even so, that means this code, if it were working properly, should just be passing signal through (since `real` and `imag` never get modified, and are then written back into the `out` buffer). The stuttering is likely an audio buffer underflow issue. Can you increase the audio buffer size, and reduce the number of overlaps and / or FFT size?

**Comment by GuitarML** [comment]
Thanks for your response! I'll try out the new granular build out soon, and yes I think my code is not able to keep up properly on the Daisy as written. I might try setting the amp out to 1 and see if it changes anything, thanks!

**Comment by GuitarML** [comment]
@amcerbu that was the problem! The *= on calculating reverb amp the first time was a typo, should have just been "=". I got some significant stuttering, but reducing the samplerate to 32khz made it run smoothly, and it sounds really cool. Any tips on improving the efficiency? Or is this fft implementation about as good as it will get on the daisy seed. 

Thanks so much for your help! I'll share the full code soon.

**Comment by amcerbu** [comment]
@GuitarML Glad you got it working! I suspect there are some optimizations possible in my STFT classes…. I haven’t had much time to play with this recently but I’d love to squeeze out some more performance. Looking forward to playing around with your project when you share it!

**Comment by GuitarML** [comment]
Here's my project using your FFT example and based on the reverb code above:

https://github.com/GuitarML/FunBox/tree/main/software/Venus

I did a demo video and put it on the Daisy forum, tagged you for the original example code. Thanks again for making sharing that!

**Comment by GuitarML** [comment]
@amcerbu one more question, I'll close the thread after this since it's more of a discussion and no issue with the code. 

Does the process() custom function get called once per sample of audio? I.e., at the samplerate set for the Daisy Seed? I'm interested in implementing a delay line into the FFT analysis, and I'm wondering if it's as easy as writing the real component (or real and imag?) of the analysis to a delay line, and processing it within the custom function. I wasn't sure how that worked with the overlapping windows. 

Thanks!

**Comment by amcerbu** [comment]
@GuitarML the `process` function is called every `N / laps` samples, and transforms one window's worth of frequency domain data – do you want delay in the time domain? Or across analysis windows? You can definitely do the latter, but it is a bit more resource intensive, since, unless you're delaying only certain frequencies, you'd need your delay line to store some number of `N`-channel analysis frames.

**Comment by GuitarML** [comment]
Got it, yeah I was interested in delaying different bins by different rates in the time domain. I'd like to see if I can replicate the spectral delay Puredata patch from this post:

https://guitarextended.wordpress.com/2012/02/07/spectral-delay-effect-for-guitar-with-pure-data/

There's a SoundCloud recording of it at the end of the article. Sounds pretty cool!
